---
RNN:
  in_feat_dim: 6
  hidden_state_dim: 256
  out_feat_dim: 32
  num_layers: 2
  sequence_length: 30
  batch_first: true
  bidirectional: false
  use_all_outputs: false
  applied_data_list:
  - hold_time
  - inter_time
  - distance
  - speed

GRU:
  in_feat_dim: 6
  hidden_state_dim: 256
  out_feat_dim: 32
  num_layers: 2
  sequence_length: 30
  batch_first: true
  bidirectional: false
  use_all_outputs: false
  applied_data_list:
  - hold_time
  - inter_time
  - distance
  - speed

FCNetwork:
  in_feat_dim: 6
  input_size: 2
  hidden_size: 64
  output_size: 32
  use_batch_norm: true
  sequence_length: 30
  gesture_type_embedding_dim: 8
  applied_data_list:
  - hold_time
  - inter_time
  - distance
  - speed


LSTM:
  in_feat_dim: 6
  hidden_state_dim: 256
  out_feat_dim: 32
  num_layers: 2
  sequence_length: 30
  batch_first: true
  bidirectional: false
  use_all_outputs: false
  applied_data_list:
  - hold_time
  - inter_time
  - distance
  - speed