---
RNN:
  input_size: 1
  hidden_size: 64
  num_layers: 1
  nonlinearity: 'relu'
  bias: true
  batch_first: true
  dropout: 0.0
  bidirectional: true

GRU:
  in_feat_dim: 1
  hidden_state_dim: 64
  out_feat_dim: 32
  num_layers: 1
  sequence_length: 30
  batch_first: true
  bidirectional: true
  use_all_outputs: false
  applied_data_list:
  - hold_time
  - inter_time
  - distance
  - speed

FCNetwork:
  in_feat_dim: 1
  input_size: 1
  hidden_size: 64
  output_size: 32
  use_batch_norm: true
  sequence_length: 30
  gesture_type_embedding_dim: 8
  applied_data_list:
  - hold_time
  - inter_time
  - distance
  - speed